name: gis_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal>=3.8
  - geopandas>=0.14
  - rasterio>=1.3
  - rasterstats
  - numpy
  - pandas
  - matplotlib
  - shapely
  - fiona
  - pyproj
  - scipy
  - jupyter
